### ISSUE TITLE
Can we get access to some of the core DBT models as a reference

### ISSUE THREAD

**Issue by e0d** [openedx/wg-data#18]
Reach out to edX data engineering to see if we can get a one time dump of any dbt models that are not edx.org specific. Then sort out and contextualize them into a document or project as a reference implementation.

**Comment by bmtcril** [comment]
I've reached out to Bob and Troy at edX about this, waiting to hear back.

**Comment by bmtcril** [comment]
2U has tickets on the DE board now to share out a set of dbt models and necessary project structure as a reference for the community. So just waiting on that drop to move this forward. I'll likely post it on Discuss with some context on what it all means and try to keep the questions from impacting 2U much.

**Comment by Ian2012** [comment]
@bmtcril I will close this issue as the current implementation lives under https://github.com/openedx/aspects-dbt

**Comment by bmtcril** [comment]
This isn't the same thing, but I did get the things I was looking for a little bit ago so it can be closed!
