### ISSUE TITLE
Move analytics related documentation to the new site

### ISSUE THREAD

**Issue by bmtcril** [openedx/wg-data#20]
A lot of good information on our event system exists in various places. Notably: 

https://edx.readthedocs.io/projects/devdata/en/stable/internal_data_formats/tracking_logs.html
https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0026-arch-realtime-events.html
https://event-routing-backends.readthedocs.io/en/latest/

as well as several Confluence pages.

This task is to create a new space in docs.openedx.org for data and analytics documentation and begin moving old pages there, and creating pointers to existing docs from a centralized location. 

Documentation should include things like:

- [x] Move existing documentation of events from the openedx space 
- [ ] How to capture tracking log data on disk and in Mongo
- [ ] Pointers to Insights existing docs
- [ ] How to use xAPI to collect and report events

**Comment by jmakowski1123** [comment]
part of event documentation milestone

**Comment by Ian2012** [comment]
Is there already a section for data and analytics in https://docs.openedx.org/en/latest/?

**Comment by bmtcril** [comment]
Most of this is developer documentation, so would end up under there. We can also document things in other repos and link them back to the main docs site as we did with openedx-oars, so in general if the documentation is specific to a repository it's best to create it there and then link back to it from the docs repo.
