### ISSUE TITLE
Docs: Move developer guide analytics page

### ISSUE THREAD

**Issue by bmtcril** [openedx/wg-data#23]
This page has a combination of very relevant useful information and outdated / incorrect information. We'd like to move it into docs.openedx.org! This will include reformatting it into several different docs, which may include duplicating some content. This is ok! Here are some docs on how to get started writing docs: https://docs.openedx.org/en/latest/documentors/index.html

Original doc:
https://edx.readthedocs.io/projects/edx-developer-guide/en/latest/analytics.html

Bonus doc, which has some edx.org oriented additional flavor text that may or may not be useful to bring in as this gets fleshed out: https://openedx.atlassian.net/wiki/spaces/DE/pages/2919432202/Analytical+event+flow+2021

Things to add:

- I would like to add explicit how-to docs about the lifecycle of events. These should explicitly include adding native events (6.1.1. of this doc) and how to plumb for xAPI and Caliper with pointers to event-routing-backends docs. Some of these processes may not exist yet! You can draft sensible suggestions for review or ask the Data WG to draft some.
  - Adding an event
  - Testing an event
  - Documenting an event
  - Modifying + versioning an event
  - Deprecation and removal of an event

Structural updates:

- I think that the header content in sections 6 and 6.1, and all of 6.1.3, 6.1.4, and 6.2* can go in a Developers -> Concepts doc. That doc should also touch on event-routing-backends / xAPI / Caliper at a surface level
- 6.1.1 through 6.1.1.5 and 6.1.2 can go in the how-to docs above
 

Content that will need updating off the top of my head:

6.1.1. Javascript event emission, I'm not sure how true this is now or what the current state of this emission is, we should ask the frontend working group and update as necessary.

6.1.1.5. and any other devstack references

6.1.1.6.2. The test code here is very old and should be updated to be more modern (no classes, pytest, etc)

6.1.1.6.3. Bokchoy references can be removed

6.1.2. Will need to be updated to point at the new docs

6.1.4. I guess this situation is not temporary.

**Comment by e0d** [comment]
@bmtcril is this still reasonably accurate?

https://openedx.atlassian.net/wiki/spaces/AN/pages/13959562/Code+Snippets

**Comment by bmtcril** [comment]
@e0d yes-ish. I think it needs a refresh for Tutor and how MFEs handle sending events, which I think is fairly different than doing it through the LMS frontend code. I think it needs some more context around the overall event lifecycle as above, too, but could definitely be used as a base for the updated doc.
