### ISSUE TITLE
Update event docs to include new Olive events

### ISSUE THREAD

**Issue by bmtcril** [openedx/wg-data#25]
Some new events have been added in Olive that should also be represented in the event reference docs here: https://docs.openedx.org/en/latest/developers/references/internal_data_formats/index.html

The new events are listed here: https://edx--2093.org.readthedocs.build/projects/open-edx-release-notes/en/2093/olive.html#researcher-data-experiences

And details on the events are here: https://docs.google.com/spreadsheets/d/1YoOWlodw6lutfI-8pDZDRIOqjo6J9D5L2SuENn-mXmQ/edit?usp=sharing

Some research will need to be done to get the details of each event, but it shouldn't be too bad.

AC:

- [ ] A PR has been merged adding the new events to docs.openedx.org

**Comment by Ian2012** [comment]
assign me

**Comment by bmtcril** [comment]
Looks good, I merged it! Going to call this done.
