### ISSUE TITLE
Compare existing xAPI events with related profiles and create a list of appropriate changes

### ISSUE THREAD

**Issue by e0d** [openedx/wg-data#7]
Focus on the video profile, which is the only one we approach implementing.  Where are our existing xAPI events not aligned with the profile.

AC:
- A backlog to implement the profile.

**Comment by bmtcril** [comment]
@e0d I think we can close this in favor of #5 ?

**Comment by e0d** [comment]
I think this is a little different.  This is the work that I've actually done for the video profile.  I don't think there's another profile that I would consider worth investigating today.

The out was the list of tickets for the xAPI video profile milestone.

https://github.com/openedx/event-routing-backends/milestone/1

I think we should close this as done.

**Comment by Ian2012** [comment]
@e0d I will close this issue, please feel free to open if this is still a needed
